<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class CreateTask extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>'required|max:255',
            'project_id'=>'required|integer|exists:projects,id',
        ];
    }
    public function failedValidation(Validator $validator)
    {
        $this->errorBag='create';
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
