<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Contracts\Validation\Validator;

class UpdateTask extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>'required|max:255',
            'project_id'=>[
                'required',
                 'integer',
                 Rule::exists('projects','id')
                     ->where(function($query){
                         return $query->whereIn('id',$this->user()->projects()->pluck('id'));
                     })
            ],
        ];
    }
    public function failedValidation(Validator $validator)
    {
        $this->errorBag='update_'.$this->route('tasks');
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
