<?php

namespace App\Http\Requests;

use App\User;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>[
                'required',
                 Rule::unique('projects')->ignore($this->route('projects'))->where(function($query){
                     $query->where('user_id',request()->user()->id);
                 })
            ],
            'thumbnail'=>'image'
        ];
    }
    public function messages()
    {
        return [
            'name.required'=>'请填写项目名称',
            'name.unique'=>'项目名称重复',
            'thumbnail'=>'请上传正确的图片'
        ];
    }
    public function failedValidation(Validator $validator)
    {
        $this->errorBag='update_'.$this->route('projects');
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
